import { marked, type Token, type TokenizerExtension } from "marked";

export type WalliChatCustomBlockMeasureContext = {
  availableWidth: number;
};

export type WalliChatCustomBlockMetrics = {
  height: number;
  width?: number;
};

export type WalliChatCustomBlockRenderContext<T> = {
  contentInsetX: number;
  data: T;
  height: number;
  left: number;
  top: number;
  width: number;
};

export type WalliChatCustomBlockTokenizer<T> = {
  level?: "block";
  tokenize: (
    source: string,
    tokens: readonly Token[],
  ) => { data: T; raw: string } | undefined;
};

export type WalliChatCustomBlockDefinition<T = unknown> = {
  /** A stable, globally unique name for this block type. */
  name: string;
  /** Gap above the block, in pixels. */
  marginTop?: number;
  measure: (
    data: T,
    context: WalliChatCustomBlockMeasureContext,
  ) => WalliChatCustomBlockMetrics;
  render: (context: WalliChatCustomBlockRenderContext<T>) => unknown;
  /** CSS injected into this block's isolated Shadow Root. Accepts CSS generated by UnoCSS. */
  styles?: string | readonly string[];
  tokenizer: WalliChatCustomBlockTokenizer<T>;
};

export type WalliChatCustomBlockRegistration = {
  unregister: () => void;
};

type AnyCustomBlockDefinition = WalliChatCustomBlockDefinition<unknown>;

const definitions = new Map<string, AnyCustomBlockDefinition>();
const tokenTypePrefix = "walli-custom-block-";

export function registerCustomBlock<T>(
  definition: WalliChatCustomBlockDefinition<T>,
): WalliChatCustomBlockRegistration {
  const name = definition.name.trim();
  if (name.length === 0) throw new Error("Custom block name cannot be empty");
  if (definitions.has(name)) throw new Error(`Custom block \"${name}\" is already registered`);

  const stored = definition as AnyCustomBlockDefinition;
  definitions.set(name, stored);

  const extension: TokenizerExtension = {
    level: definition.tokenizer.level ?? "block",
    name: `${tokenTypePrefix}${name}`,
    tokenizer(source, tokens) {
      if (definitions.get(name) !== stored) return undefined;
      const result = definition.tokenizer.tokenize(source, tokens);
      if (!result) return undefined;
      if (result.raw.length === 0) {
        throw new Error(`Custom block \"${name}\" tokenizer returned an empty raw value`);
      }
      return {
        type: `${tokenTypePrefix}${name}`,
        raw: result.raw,
        walliCustomBlockData: result.data,
      };
    },
  };
  marked.use({ extensions: [extension] });

  return {
    unregister() {
      if (definitions.get(name) === stored) definitions.delete(name);
    },
  };
}

export function resolveCustomBlockToken(
  token: Token,
): { data: unknown; definition: AnyCustomBlockDefinition } | null {
  if (!token.type.startsWith(tokenTypePrefix)) return null;
  const definition = definitions.get(token.type.slice(tokenTypePrefix.length));
  if (!definition) return null;
  const data = (token as Token & { walliCustomBlockData?: unknown }).walliCustomBlockData;
  return { data, definition };
}

export type { AnyCustomBlockDefinition };
