name = "walli_core"
main = "./src/worker/index.ts"
compatibility_date = "2025-10-08"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[ai]
binding = "AI"

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "walli_core"
database_id = "a64f7d00-ad98-4e14-ad7f-1162a3e21a11"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "APP_KV"
id = "a3ead2192a94459db359c9d11e47bc92"
