import { marked, type Token, type TokenizerExtension } from "marked";
import { html, render, type TemplateResult } from "lit";
import { customElement } from "lit/decorators.js";
import type { BlockLayout } from "../type";
import { BlockShellElement } from "./block-shell";

export type WalliChatBlockMeasureContext = {
  availableWidth: number;
};

export type WalliChatBlockMetrics = {
  height: number;
  width?: number;
};

export type WalliChatTokenizedBlockRenderContext<T> = {
  contentInsetX: number;
  data: T;
  height: number;
  left: number;
  top: number;
  width: number;
};

export type WalliChatBlockTokenizer<T> = {
  level?: "block";
  tokenize: (source: string, tokens: readonly Token[]) => { data: T; raw: string } | undefined;
};

export type WalliChatTokenizedBlockDefinition<T = unknown> = {
  /** A stable, globally unique name for this block type. */
  name: string;
  /** Gap above the block, in pixels. */
  marginTop?: number;
  measure: (data: T, context: WalliChatBlockMeasureContext) => WalliChatBlockMetrics;
  render: (context: WalliChatTokenizedBlockRenderContext<T>) => unknown;
  /** CSS injected into this block's isolated Shadow Root. Accepts CSS generated by UnoCSS. */
  styles?: string | readonly string[];
  tokenizer: WalliChatBlockTokenizer<T>;
};

export type WalliChatTokenizedBlockRegistration = {
  unregister: () => void;
};

type AnyCustomBlockDefinition = WalliChatTokenizedBlockDefinition<unknown>;

const definitions = new Map<string, AnyCustomBlockDefinition>();
const tokenTypePrefix = "walli-custom-block-";

export function registerTokenizedBlock<T>(
  definition: WalliChatTokenizedBlockDefinition<T>,
): WalliChatTokenizedBlockRegistration {
  const name = definition.name.trim();
  if (name.length === 0) throw new Error("Custom block name cannot be empty");
  // if (definitions.has(name)) throw new Error(`Custom block \"${name}\" is already registered`);

  const stored = definition as AnyCustomBlockDefinition;
  definitions.set(name, stored);

  const extension: TokenizerExtension = {
    level: definition.tokenizer.level ?? "block",
    name: `${tokenTypePrefix}${name}`,
    tokenizer(source, tokens) {
      if (definitions.get(name) !== stored) return undefined;
      const result = definition.tokenizer.tokenize(source, tokens);
      if (!result) return undefined;
      if (result.raw.length === 0) {
        throw new Error(`Custom block \"${name}\" tokenizer returned an empty raw value`);
      }
      return {
        type: `${tokenTypePrefix}${name}`,
        raw: result.raw,
        walliCustomBlockData: result.data,
      };
    },
  };
  marked.use({ extensions: [extension] });

  return {
    unregister() {
      if (definitions.get(name) === stored) definitions.delete(name);
    },
  };
}

export function resolveCustomBlockToken(
  token: Token,
): { data: unknown; definition: AnyCustomBlockDefinition } | null {
  if (!token.type.startsWith(tokenTypePrefix)) return null;
  const definition = definitions.get(token.type.slice(tokenTypePrefix.length));
  if (!definition) return null;
  const data = (token as Token & { walliCustomBlockData?: unknown }).walliCustomBlockData;
  return { data, definition };
}

export type { AnyCustomBlockDefinition };

type CustomBlockLayout = Extract<BlockLayout, { kind: "custom" }>;
type CustomBlockContentLayout = {
  data: unknown;
  definition: AnyCustomBlockDefinition;
  height: number;
  width: number;
};

const customStyleSheetCache = new Map<string, CSSStyleSheet>();

@customElement("walli-custom-block-content")
export class WalliCustomBlockContentElement extends HTMLElement {
  private readonly contentElement = document.createElement("div");
  private readonly root: ShadowRoot;
  private readonly styleElement = document.createElement("style");
  private currentStyles = "";

  constructor() {
    super();
    this.root = this.attachShadow({ mode: "open" });
    this.contentElement.style.height = "100%";
    this.contentElement.style.position = "relative";
    this.contentElement.style.width = "100%";
    this.styleElement.setAttribute("data-walli-custom-block-styles", "");
    this.root.append(this.contentElement);
  }

  set layout(layout: CustomBlockContentLayout) {
    const styles = normalizeStyles(layout.definition.styles);
    if (styles !== this.currentStyles) {
      this.currentStyles = styles;
      this.applyStyles(styles);
    }

    render(
      layout.definition.render({
        contentInsetX: 0,
        data: layout.data,
        height: layout.height,
        left: 0,
        top: 0,
        width: layout.width,
      }),
      this.contentElement,
    );
  }

  private applyStyles(styles: string): void {
    if (supportsConstructableStyleSheets(this.root)) {
      try {
        if (styles.length === 0) {
          this.root.adoptedStyleSheets = [];
        } else {
          let sheet = customStyleSheetCache.get(styles);
          if (sheet === undefined) {
            sheet = new CSSStyleSheet();
            sheet.replaceSync(styles);
            customStyleSheetCache.set(styles, sheet);
          }
          this.root.adoptedStyleSheets = [sheet];
        }
        this.styleElement.remove();
        return;
      } catch {
        this.root.adoptedStyleSheets = [];
      }
    }

    this.styleElement.textContent = styles;
    if (!this.styleElement.isConnected) {
      this.root.insertBefore(this.styleElement, this.contentElement);
    }
  }
}

function supportsConstructableStyleSheets(root: ShadowRoot): boolean {
  return "adoptedStyleSheets" in root && "replaceSync" in CSSStyleSheet.prototype;
}

function normalizeStyles(styles: string | readonly string[] | undefined): string {
  if (styles === undefined) return "";
  return typeof styles === "string" ? styles : styles.join("\n");
}

@customElement("walli-custom-block")
export class WalliCustomBlockElement extends BlockShellElement<CustomBlockLayout> {
  protected override renderContent(
    block: CustomBlockLayout,
    contentInsetX: number,
  ): TemplateResult {
    return html`<walli-custom-block-content
      class="absolute block overflow-hidden"
      style=${`left:${contentInsetX + block.contentLeft}px;top:0;width:${block.width}px;height:${block.height}px;`}
      .layout=${{
        data: block.data,
        definition: block.definition,
        height: block.height,
        width: block.width,
      }}
    ></walli-custom-block-content>`;
  }
}
