import { registerBlock } from "../block-registry";
import { assetsGroupBlockDefinition } from "./assets-group-block";
import { codeBlockDefinition } from "./code-block";
import { customBlockDefinition } from "./custom-block";
import { imageBlockDefinition } from "./image-block";
import { inlineBlockDefinition } from "./inline-block";
import { loadingBlockDefinition } from "./loading-block";
import { ruleBlockDefinition } from "./rule-block";
import { startBlockDefinition, toolCallBlockDefinition } from "./stream-block";
import { tableBlockDefinition } from "./table-block";

registerBlock(assetsGroupBlockDefinition);
registerBlock(codeBlockDefinition);
registerBlock(customBlockDefinition);
registerBlock(imageBlockDefinition);
registerBlock(inlineBlockDefinition);
registerBlock(ruleBlockDefinition);
registerBlock(tableBlockDefinition);
registerBlock(loadingBlockDefinition);
registerBlock(startBlockDefinition);
registerBlock(toolCallBlockDefinition);

export { assetsGroupBlockDefinition };
export { codeBlockDefinition };
export { customBlockDefinition };
export { imageBlockDefinition };
export { inlineBlockDefinition };
export { loadingBlockDefinition };
export { ruleBlockDefinition };
export { tableBlockDefinition };
